### ISSUE TITLE
Erro ao executar a fila com múltiplas tags

### ISSUE THREAD

**Issue by arthost** [rodtanci/ChatWoot-Disparador-de-Campanhas#1]
Ao tentar rodar a campanha com múltiplas tags, esta gerando o erro "No data found for item-index: "1" [item 1]" como na imagem abaixo:

![image](https://github.com/user-attachments/assets/4ec1bf64-8308-4ad6-8aec-f2a9112ec659)

O erro acontece apartir do segundo item:

![image](https://github.com/user-attachments/assets/4d2fb09b-9487-4d2c-8b6b-d99a506816da)

O problema acontece pelo codigo: "{{ $node['Info_Base'].json.chatwoot_account_id }}"

Com acesso usando "{{ $('Info_Base').item.json.chatwoot_account_id }}" não acontece.

**Comment by rodtanci** [comment]
Obrigado pelo informativo, correção em andamento!

**Comment by rodtanci** [comment]
Correção aplicada na versão 1.8.
