### ISSUE TITLE
Posso usar arquivos compartilhados pelo Google Drive?

### ISSUE THREAD

**Issue by danielfontolan** [rodtanci/ChatWoot-Disparador-de-Campanhas#3]
O disparador aceita imagens compartilhadas que não terminam em .JPG? Aceita um compartilhamento do Google Drive por exemplo? Não consegui fazer funcionar pelo Google Drive.

**Comment by rodtanci** [comment]
O link precisa conter a imagem direta e terminar com .jpg ou .png

**Comment by danielfontolan** [comment]
obrigado!
